[package]
name = "osc_parser"
version = "0.1.0"
edition = "2021"
#crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosc = "~0.10"
interoptopus = "~0.14.23"
interoptopus_backend_csharp = "~0.14.24"